name: Update Badges

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # runs daily

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Count courses
        run: |
          count=$(grep -o "Redeem Here" README.md | wc -l)
          echo "TOTAL_COURSES=$count" >> $GITHUB_ENV

      - name: Update badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GITHUB_TOKEN }}
          gistID: your_gist_id
          filename: courses.json
          label: Total Courses
          message: ${{ env.TOTAL_COURSES }}
          color: orange
